"""
mental_health_support.py — Empathy engine scaffolding, coping toolkit, safe prompts
and AI-independent fallbacks for HAVEN's mental-health module.

Everything here is deterministic DATA + prompt construction. The actual empathetic
prose for NON-crisis turns is generated by the LLM using `build_system_prompt(...)`,
but crisis turns, medication-safety refusals and AI-outage fallbacks are answered
from the fixed, reviewed text in this file so they NEVER depend on a model being up
or honest (spec §16, §18, §25, §29).

No diagnosis, no medication doses, no fabricated resources — resource content comes
only from `mental_health_resources.py`.
"""
from __future__ import annotations

from typing import Any, Dict, List, Optional

from services import mental_health_resources as R
from services import mental_health_triage as TR

SUPPORT_VERSION = "2026-09-25"
DISCLAIMER = R.DISCLAIMER

# ─────────────── Mental-health system prompt (spec §16, §6, §7, §17) ───────────────
_BASE_SYSTEM_PROMPT = """You are a warm, supportive companion inside HAVEN, a women's safety app. \
You offer emotional support and help people find real help. You are NOT a doctor, \
psychiatrist, therapist, or emergency service, and you never claim to be one.

HOW TO RESPOND (normal support):
- Acknowledge the feeling first, with genuine warmth.
- Reflect back what you heard WITHOUT assuming or labelling it.
- Offer one or two small, practical, low-risk options.
- Suggest one small next step, then ask ONE gentle follow-up question.
- Encourage support from trusted people and professionals; remind them they deserve \
real human support, not only an app.
- Keep it concise: 2-4 short sentences. Be shorter when distress is high.

NEVER:
- Diagnose or name a condition. Do not say the person "has" depression, anxiety, PTSD, \
bipolar disorder, a panic disorder, etc. Instead say feelings can happen for many \
reasons and a mental-health professional can help understand what's going on.
- Give medicine names, doses, or say whether to start, stop, or mix any medication.
- Claim certainty about mental illness or the future, or tell the person they are \
definitely safe when that cannot be known.
- Invent helplines, professionals, or resources. Only refer to resources you are given.
- Build dependency ("only talk to me", "you don't need anyone else", "I'm all you \
need"), use guilt or shame, discourage professional help, or encourage isolation or \
romantic/relationship dependency.
- Pretend to be human, or claim you have contacted anyone.

Be honest, gentle, and respectful of the person's autonomy."""


def build_system_prompt(triage: TR.MHTriage, language: str) -> str:
    """Assemble the safety-hardened system prompt for a NON-crisis support turn."""
    lang_name = {"hi": "Hindi", "hinglish": "Hinglish (romanised Hindi)"}.get(language, "English")
    parts = [_BASE_SYSTEM_PROMPT, f"\nReply in {lang_name}."]
    if triage.response_mode == TR.MODE_MODERATE:
        parts.append("The person is in noticeable distress — be especially gentle, keep it "
                     "short, and do not overwhelm them with options.")
    if triage.needs_clarification and triage.clarifying_question:
        parts.append("Gently and directly ask this one safety question in your reply: "
                     f"\"{triage.clarifying_question}\"")
    if triage.minor_suspected:
        parts.append("The person may be a minor. Encourage them to reach a trusted safe adult "
                     "and appropriate professional help; never encourage secrecy from all adults.")
    return "\n".join(parts)


# ─────────────── AI-provider context minimization (spec §14, §27) ───────────────
# The ONLY user text that ever reaches the AI provider is the current non-crisis
# message plus a short, sanitized window of recent chat turns. This helper is the
# single choke-point that decides what history is allowed out, so the privacy
# dashboard can describe it truthfully. It NEVER sees safety plans, journal entries,
# mood logs or trusted-contact details — those are not part of the chat `messages`
# list and are never passed here.
_MAX_HISTORY_MESSAGES = 4          # short recent window only
_MAX_MESSAGE_CHARS = 500           # clip long turns before they leave the app
_CRISIS_TIERS = frozenset({TR.HIGH, TR.IMMINENT})


def sanitize_history(messages: Optional[List[Dict[str, Any]]],
                     redacted_marker: str,
                     *,
                     window: int = _MAX_HISTORY_MESSAGES,
                     max_chars: int = _MAX_MESSAGE_CHARS) -> List[Dict[str, Any]]:
    """Return the minimal, privacy-safe conversation window to send to the AI provider.

    Drops anything sensitive or unnecessary so the provider only ever sees ordinary,
    low-risk back-and-forth:
      * empty turns and the redaction placeholder itself (never leak the marker text),
      * user turns previously classified HIGH_RISK / IMMINENT_DANGER — crisis content
        is handled deterministically on-device and must not be echoed to the provider,
      * any role that isn't a plain user/assistant chat turn,
      * anything beyond a short recent window, each surviving turn clipped to max_chars.

    Pure and defensive: unknown shapes are skipped, never raised on.
    """
    safe: List[Dict[str, Any]] = []
    for m in messages or []:
        if not isinstance(m, dict):
            continue
        role = m.get("role")
        if role not in ("user", "assistant"):
            continue
        content = (m.get("content") or "").strip()
        if not content or content == redacted_marker:
            continue
        if role == "user" and m.get("risk_level") in _CRISIS_TIERS:
            continue
        if max_chars and len(content) > max_chars:
            content = content[:max_chars]
        safe.append({"role": role, "content": content})
    if window and window > 0:
        safe = safe[-window:]
    return safe


# ─────────────────────────── Coping toolkit (spec §8) ───────────────────────────
# Evidence-informed, low-risk SUPPORT STRATEGIES — explicitly not medical treatment.
_TOOLS: Dict[str, Dict[str, Any]] = {
    "breathing": {
        "id": "breathing", "title": "Slow breathing", "category": "calming",
        "steps": ["Breathe in gently through your nose for 4 counts.",
                  "Hold for 4 counts.", "Breathe out slowly for 6 counts.",
                  "Repeat 4-6 times."],
        "caution": "Stop if you feel light-headed or uncomfortable.",
    },
    "grounding_54321": {
        "id": "grounding_54321", "title": "5-4-3-2-1 grounding", "category": "grounding",
        "steps": ["Name 5 things you can see.", "Name 4 things you can feel or touch.",
                  "Name 3 things you can hear.", "Name 2 things you can smell.",
                  "Name 1 thing you can taste, or take one slow breath."],
        "caution": "Go at your own pace — there is no wrong answer.",
    },
    "present_moment": {
        "id": "present_moment", "title": "Come back to the present", "category": "grounding",
        "steps": ["Say today's date and where you are, out loud if you can.",
                  "Notice your feet on the floor and the seat beneath you.",
                  "Pick one small, safe action you can do in the next minute."],
        "caution": "This is to help you feel steadier, not to fix everything at once.",
    },
    "emotional_labeling": {
        "id": "emotional_labeling", "title": "Name the feeling", "category": "reflection",
        "steps": ["Ask yourself: what emotion fits best right now?",
                  "Is it one feeling, or a few mixed together?",
                  "Naming it can make it feel a little more manageable."],
        "caution": "There are no wrong feelings.",
    },
    "problem_breakdown": {
        "id": "problem_breakdown", "title": "Break it down", "category": "problem_solving",
        "steps": ["What exactly happened?", "What part can I control right now?",
                  "What needs someone else's help?", "What can safely wait until later?"],
        "caution": "You don't have to solve everything today.",
    },
    "sleep_support": {
        "id": "sleep_support", "title": "Wind-down for sleep", "category": "sleep",
        "steps": ["Dim screens and lights about an hour before bed.",
                  "Try the same wind-down routine each night.",
                  "If your mind races, jot the thoughts on paper to return to tomorrow."],
        "caution": "This is general sleep hygiene, not medical advice — no medication guidance.",
    },
    "study_work_stress": {
        "id": "study_work_stress", "title": "Study / work reset", "category": "stress",
        "steps": ["Pick the single most urgent task.", "Break it into one small first step.",
                  "Work for a short focused block, then take a real break."],
        "caution": "Small steps count — progress over perfection.",
    },
    "loneliness": {
        "id": "loneliness", "title": "Reaching out", "category": "connection",
        "steps": ["Think of one person you feel a little safe with.",
                  "Send a short, low-pressure message — even just 'hi'.",
                  "Consider one small structured social step this week."],
        "caution": "Connection can take small tries — that's okay.",
    },
    "grief": {
        "id": "grief", "title": "Living with grief", "category": "grief",
        "steps": ["Let the feelings come in waves — they don't have a timetable.",
                  "Keep gentle routines like meals, water, and rest.",
                  "Lean on people or a support group who can sit with you in it."],
        "caution": "Grief is not a problem to be fixed, and support helps.",
    },
}
for _t in _TOOLS.values():
    _t["type"] = "support_strategy"


def get_tool(tool_id: str) -> Optional[Dict[str, Any]]:
    t = _TOOLS.get(tool_id)
    return dict(t) if t else None


def all_tools() -> List[Dict[str, Any]]:
    return [dict(t) for t in _TOOLS.values()]


def coping_tools_for(triage: TR.MHTriage, limit: int = 3) -> List[Dict[str, Any]]:
    """Pick a small, relevant set of coping tools for this message (deterministic)."""
    text = TR._norm(triage.raw_message)
    if triage.crisis:
        chosen = ["grounding_54321", "breathing"]
    else:
        chosen: List[str] = []
        if TR._any(text, ["sleep", "insomnia", "can't sleep", "cant sleep", "neend", "नींद"]):
            chosen.append("sleep_support")
        if TR._any(text, ["exam", "study", "work", "job", "office", "deadline", "padhai", "पढ़ाई"]):
            chosen.append("study_work_stress")
        if TR._any(text, ["lonely", "alone", "akela", "akeli", "अकेल", "no one", "nobody"]):
            chosen.append("loneliness")
        if TR._any(text, ["grief", "grieving", "died", "passed away", "loss", "miss ", "lost my",
                          "शोक", "मौत"]):
            chosen.append("grief")
        if TR._any(text, ["panic", "anxiety", "anxious", "worry", "worried", "overwhelm",
                          "ghabra", "घबरा", "डर"]):
            chosen += ["breathing", "grounding_54321", "present_moment"]
        if triage.risk_level == TR.MODERATE:
            chosen += ["breathing", "grounding_54321", "problem_breakdown"]
        chosen += ["breathing", "emotional_labeling"]
    out, seen = [], set()
    for tid in chosen:
        if tid in _TOOLS and tid not in seen:
            seen.add(tid)
            out.append(dict(_TOOLS[tid]))
        if len(out) >= limit:
            break
    return out


# ─────────── Deterministic responses (crisis / medication / AI-outage) ───────────
# These are AI-INDEPENDENT so they always work, even if the LLM is down or unsafe.
_IMMINENT_TEXT = {
    "en": ("Your safety matters more than anything else right now. If you are in immediate "
           "danger or have hurt yourself, please call 112 now. If you can, be near another "
           "person or move somewhere safer. Tele-MANAS (14416) has trained counsellors 24x7. "
           "Can you call one of these now, or would you like to use HAVEN SOS?"),
    "hi": ("अभी आपकी सुरक्षा सबसे ज़रूरी है। अगर आप तुरंत खतरे में हैं या आपने खुद को नुकसान "
           "पहुँचाया है, तो कृपया अभी 112 पर कॉल करें। अगर हो सके तो किसी के पास रहें या सुरक्षित "
           "जगह जाएँ। टेली-मानस (14416) पर प्रशिक्षित काउंसलर 24x7 उपलब्ध हैं। क्या आप अभी कॉल कर "
           "सकती हैं, या HAVEN SOS इस्तेमाल करना चाहेंगी?"),
    "hinglish": ("Abhi aapki safety sabse zaroori hai. Agar aap turant khatre mein hain ya khud "
                 "ko nuksan pahuncha liya hai, to please abhi 112 par call karein. Ho sake to kisi "
                 "ke paas rahein ya safe jagah jaayein. Tele-MANAS (14416) par trained counsellor "
                 "24x7 available hain. Kya aap abhi call kar sakti hain, ya HAVEN SOS use karna "
                 "chahengi?"),
}
_HIGH_TEXT = {
    "en": ("I'm really glad you told me, and I'm sorry you're carrying something this heavy. "
           "You don't have to go through it alone. Talking to someone now can help — Tele-MANAS "
           "(14416) has caring, trained counsellors available 24x7, and a trusted person can be "
           "with you too. Would you like to call Tele-MANAS, reach a trusted contact, or use "
           "HAVEN SOS?"),
    "hi": ("आपने बताया, इसके लिए शुक्रिया — और मुझे दुख है कि आप इतना भारी बोझ उठा रही हैं। आपको "
           "यह अकेले नहीं झेलना है। अभी किसी से बात करना मदद कर सकता है — टेली-मानस (14416) पर "
           "प्रशिक्षित, सहानुभूति रखने वाले काउंसलर 24x7 मौजूद हैं, और कोई भरोसेमंद व्यक्ति भी आपके "
           "साथ हो सकता है। क्या आप टेली-मानस पर कॉल करना चाहेंगी, किसी भरोसेमंद को बुलाना, या "
           "HAVEN SOS इस्तेमाल करना?"),
    "hinglish": ("Aapne bataya, iske liye shukriya — aur mujhe dukh hai ki aap itna heavy bojh "
                 "utha rahi hain. Aapko ye akele nahi jhelna hai. Abhi kisi se baat karna madad "
                 "kar sakta hai — Tele-MANAS (14416) par trained, caring counsellor 24x7 hain, aur "
                 "koi bharosemand vyakti bhi aapke saath ho sakta hai. Kya aap Tele-MANAS call "
                 "karna chahengi, kisi trusted contact ko, ya HAVEN SOS use karna?"),
}
_MEDICATION_TEXT = {
    "en": ("I can't give medicine names, doses, or advice on mixing medicines — that could be "
           "dangerous, and only a doctor or pharmacist can guide that safely. If you've already "
           "taken more than prescribed or feel unwell, please call 112 now. For emotional support, "
           "Tele-MANAS (14416) is there 24x7. Would you like help reaching one of these?"),
    "hi": ("मैं दवा का नाम, मात्रा या दवाओं को मिलाने की सलाह नहीं दे सकती — यह खतरनाक हो सकता है, "
           "और इसे सुरक्षित रूप से सिर्फ़ डॉक्टर या फार्मासिस्ट बता सकते हैं। अगर आपने तय मात्रा से "
           "ज़्यादा ले लिया है या तबीयत ठीक नहीं है, तो कृपया अभी 112 पर कॉल करें। भावनात्मक सहारे "
           "के लिए टेली-मानस (14416) 24x7 है। क्या मैं इनमें से किसी तक पहुँचने में मदद करूँ?"),
    "hinglish": ("Main medicine ka naam, dose ya medicines mix karne ki advice nahi de sakti — ye "
                 "khatarnaak ho sakta hai, aur ise safely sirf doctor ya pharmacist bata sakte "
                 "hain. Agar aapne prescribed se zyada le liya hai ya tabiyat theek nahi, to please "
                 "abhi 112 call karein. Emotional support ke liye Tele-MANAS (14416) 24x7 hai. Kya "
                 "main inme se kisi tak pahunchne mein madad karun?"),
}
_AI_DOWN_TEXT = {
    "en": ("AI support is temporarily unavailable, but I'm still here with you. Try the grounding "
           "or breathing steps below, and remember Tele-MANAS (14416) has real people to talk to "
           "24x7. If you're in danger, call 112."),
    "hi": ("AI सहायता अभी उपलब्ध नहीं है, पर मैं आपके साथ हूँ। नीचे दिए ग्राउंडिंग या साँस के कदम "
           "आज़माएँ, और याद रखें टेली-मानस (14416) पर 24x7 असली लोग बात के लिए मौजूद हैं। अगर आप "
           "खतरे में हैं तो 112 पर कॉल करें।"),
    "hinglish": ("AI support abhi temporarily unavailable hai, par main aapke saath hoon. Neeche "
                 "diye grounding ya breathing steps try karein, aur yaad rakhein Tele-MANAS "
                 "(14416) par 24x7 real log baat ke liye hain. Agar aap khatre mein hain to 112 "
                 "call karein."),
}


def _pick_lang(mapping: Dict[str, str], language: str) -> str:
    return mapping.get(language, mapping["en"])


def crisis_response_text(triage: TR.MHTriage) -> str:
    m = _IMMINENT_TEXT if triage.risk_level == TR.IMMINENT else _HIGH_TEXT
    return _pick_lang(m, triage.language)


def medication_safety_text(language: str) -> str:
    return _pick_lang(_MEDICATION_TEXT, language)


def ai_unavailable_text(language: str) -> str:
    return _pick_lang(_AI_DOWN_TEXT, language)


def disclaimer() -> str:
    return DISCLAIMER


def emergency_resources_for(triage: TR.MHTriage) -> List[Dict[str, Any]]:
    """Emergency + crisis resources appropriate to the triage (never fabricated)."""
    child = triage.signals.get("child_safety") and triage.minor_suspected
    women = triage.signals.get("abuse")
    if triage.risk_level == TR.IMMINENT:
        base = R.emergency_resources(child=bool(child), women=bool(women))
        return base + [r for r in R.crisis_resources() if r not in base]
    if triage.crisis:
        return R.crisis_resources()
    return []


